### ISSUE TITLE
rapid collapse appearance/behaviour of box() inside of shinydashboardPlus::dashboardPage()

### ISSUE THREAD

**Issue by DavidJesse21** [RinteRface/shinydashboardPlus#105]
I am using version 2.0.0.9000 of `shinydashboardPlus`.
Using `box(collapsible=TRUE)` regardless wether it is `shinydashboard::box()` or `shinydashboardPlus::box()` inside of `shinydashboard::dashboardPage()` works fine in every way.
While `box(collapsible=TRUE)` inside of `shinydashboardPlus::dashboardPage()` still works fine in most respects, collapsing the box is rapid and not smooth anymore.
You can compare the behaviour in this example by switching between `shinydashboard::dashboardPage` and `shinydashboardPlus::dashboardPage`

```r
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)

ui <- shinydashboardPlus::dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    
    # collapsible box
    shinydashboardPlus::box(
      title = "A collapsible box",
      status = "primary",
      solidHeader = TRUE,
      width = 12,
      collapsible = TRUE,
      p("Some content...")
    )
    
  )
)

server <- function(input, output) { }

shinyApp(ui, server)
```

**Comment by nvelden** [comment]
I am experiencing exactly the same issue.

**Comment by DivadNojnarg** [comment]
See issue #69 for the cause. To change the animation speed (500 ms was the default):

```r
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)

ui <- shinydashboardPlus::dashboardPage(
  options = list(
    boxWidget = list(animationSpeed = 500)
  ),
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    
    # collapsible box
    shinydashboardPlus::box(
      title = "A collapsible box",
      status = "primary",
      solidHeader = TRUE,
      width = 12,
      collapsible = TRUE,
      p("Some content...")
    )
    
  )
)

server <- function(input, output) { }

shinyApp(ui, server)
```

**Comment by nvelden** [comment]
This does not fix the issue for me. I have the latest version (2.0.0).

**Comment by DivadNojnarg** [comment]
Could you reinstall and empty your web browser cache?

**Comment by nvelden** [comment]
That solved it thanks!
