### ISSUE TITLE
shiny 1.6.0 themes

### ISSUE THREAD

**Issue by JorisGanne** [RinteRface/shinydashboardPlus#106]
I'm excited about the new version of shiny (shiny 1.6.0) and also love the features of the package shinydashboardPlus. I was wondering if it is possible to use the bslib package to adjust the theme of a shiny app as is introduced with the new version of shiny. If it is not, becomes it possible in the future (I understand it takes some time to do) or do I need to look for another solution to combine those two nice things?

If I try to adjust the theme right now with dashboardPage and the theme argument, I receive the error message "unused argument (theme = ...)

Thanks for helping me

**Comment by DavidJesse21** [comment]
If you take a look at the [documentation](https://rinterface.github.io/shinydashboardPlus/reference/dashboardPage.html) of `shinydashboardPlus::dashboardPage()` you can see that there is no argument called `theme`.

Also you should take a look at the documentation/introduction on the `{bslib}` [website](https://rstudio.github.io/bslib/index.html).
At the bottom they refer to your question and recommend using the [`{fresh}` package](https://dreamrs.github.io/fresh/articles/vars-shinydashboard.html).

So if you use `shinydashboardPlus::dashboardPage()` you need to make use of the `freshTheme` argument.

**Comment by JorisGanne** [comment]
Thank you for the explanation, it makes the things more clear!
