### ISSUE TITLE
some functions cannot be called

### ISSUE THREAD

**Issue by chengren** [RinteRface/shinydashboardPlus#114]
Hi,
After the update, it looks like some functions such as dashboardPagePlus, dashboardHeaderPlus, cannot be called. It will return "could not find function "dashboardPagePlus" after calling.
I wonder whether it is my personal issue? Thank you so much!

**Comment by Rohit1310** [comment]
I am also facing the issue, could not find function "dashboardPagePlus" after calling,

**Comment by David-Degnan** [comment]
I am also facing this issue!

**Comment by ginberg** [comment]
there has been a major refactoring in the last version, see [news](https://github.com/RinteRface/shinydashboardPlus/blob/master/NEWS.md)
you can remove the 'Plus' from dashboardPagePlus, etc but the library shinydashboardPlus has to be loaded after shinydashboard. See basic example in [this article](https://rinterface.github.io/shinydashboardPlus/articles/shinydashboardPlus.html)

**Comment by jianhaizhang** [comment]
If so, box and boxPlus will be the same?

**Comment by ginberg** [comment]
have a look at the breaking changes in [news](https://github.com/RinteRface/shinydashboardPlus/blob/master/NEWS.md), it seems like there have been quite a bit changes for boxPlus

**Comment by DivadNojnarg** [comment]
Below is a quite complete `box` component and [here](https://rinterface.github.io/shinydashboardPlus/articles/improved-boxes.html) a entire vignette covering all boxes:

```r
library(shiny)
 library(shinydashboard)
 library(shinydashboardPlus)

 shinyApp(
   ui = dashboardPage(
     dashboardHeader(),
     dashboardSidebar(),
     dashboardBody(
      box(
        title = "Closable Box with dropdown", 
        closable = TRUE, 
        width = 12,
        status = "warning", 
        solidHeader = FALSE, 
        collapsible = TRUE,
        label = boxLabel(
         text = 1,
         status = "danger",
         style = "circle"
        ),
        dropdownMenu = boxDropdown(
         boxDropdownItem("Link to google", href = "http://www.google.com"),
         boxDropdownItem("item 2", href = "#"),
         dropdownDivider(),
         boxDropdownItem("item 3", href = "#", icon = icon("th"))
        ),
        sidebar = boxSidebar(
         startOpen = TRUE,
         id = "mycardsidebar",
         sliderInput(
          "obs", 
          "Number of observations:",
          min = 0, 
          max = 1000, 
          value = 500
         )
        ),
        plotOutput("distPlot")
       )
     )
   ),
   server = function(input, output) {
    output$distPlot <- renderPlot({
     hist(rnorm(input$obs))
    })
   }
 )
```

**Comment by jianhaizhang** [comment]
> have a look at the breaking changes in [news](https://github.com/RinteRface/shinydashboardPlus/blob/master/NEWS.md), it seems like there have been quite some changes for boxPlus

It seems `boxPlusSidebar` is not included when I run` 'boxPlusSidebar' %in% ls('package:shinydashboardPlus')`, which is mentioned in the news: Remove all sidebar related parameters from boxPlus(). This is now part of the new boxPlusSidebar().

**Comment by DivadNojnarg** [comment]
As I said I my above comment, have a look at the box [vignette](https://rinterface.github.io/shinydashboardPlus/articles/improved-boxes.html) which is the real source of truth. 

I had to push this CRAN release on a hassle (to avoid this package from being archived from CRAN) without being able to finish to reorder the `news.md` file.

**Comment by jianhaizhang** [comment]
Thanks for the reply!
