### ISSUE TITLE
tabItems / tabItem broken in 2.0?

### ISSUE THREAD

**Issue by michael-keyes** [RinteRface/shinydashboardPlus#116]
---
This works
---

```r
ui <- dashboardPage(
  header = dashboardHeader(),
  sidebar = dashboardSidebar(
  collapsed = FALSE,
  sidebarMenu(
     menuItem("Preface", tabName = "preface", icon = icon("book")
     #menuItem("Chapter 1", tabName = "ch1", icon = icon("mortar-board"),
      #menuSubItem("1.1", tabName = "ch1-1", icon = icon("angle-right")),
      #menuSubItem("1.2", tabName = "ch1-2", icon = icon("angle-right")),
      #menuSubItem("1.3", tabName = "ch1-3", icon = icon("angle-right")),
      #menuSubItem("1.4", tabName = "ch1-4", icon = icon("angle-right"))
     ),       
     menuItem("Introduction", tabName = "intro", icon = icon("book")),       
     menuItem("Chapter 1", tabName = "ch1", icon = icon("bookmark-o")),       
     menuItem("Chapter 2", tabName = "ch2", icon = icon("bookmark-o")),
     menuItem("Chapter 3", tabName = "ch3", icon = icon("bookmark-o"))
     )
  ),
  body = dashboardBody(



 ),
)
```
---
This doesn't
---
```r
ui <- dashboardPage(
  header = dashboardHeader(),
  sidebar = dashboardSidebar(
  collapsed = FALSE,
  sidebarMenu(
     menuItem("Preface", tabName = "preface", icon = icon("book")
     #menuItem("Chapter 1", tabName = "ch1", icon = icon("mortar-board"),
      #menuSubItem("1.1", tabName = "ch1-1", icon = icon("angle-right")),
      #menuSubItem("1.2", tabName = "ch1-2", icon = icon("angle-right")),
      #menuSubItem("1.3", tabName = "ch1-3", icon = icon("angle-right")),
      #menuSubItem("1.4", tabName = "ch1-4", icon = icon("angle-right"))
     ),       
     menuItem("Introduction", tabName = "intro", icon = icon("book")),       
     menuItem("Chapter 1", tabName = "ch1", icon = icon("bookmark-o")),       
     menuItem("Chapter 2", tabName = "ch2", icon = icon("bookmark-o")),
     menuItem("Chapter 3", tabName = "ch3", icon = icon("bookmark-o"))
     )
  ),
  body = dashboardBody(

  tabItems(
    #---Intro---#
    tabItem(tabName = "preface",
      fluidPage(
        h3("Preface"),
      )
    ),
    #---Intro---#
    tabItem(tabName = "intro",
      fluidPage(
        h3("Introduction"),
      )
    ),
  )

 ),
)
```

**Comment by michael-keyes** [comment]
This works:
ui <- dashboardPage(
  header = dashboardHeader(),
  sidebar = dashboardSidebar(
  collapsed = FALSE,
  sidebarMenu(
     menuItem("Preface", tabName = "preface", icon = icon("book")
     #menuItem("Chapter 1", tabName = "ch1", icon = icon("mortar-board"),
      #menuSubItem("1.1", tabName = "ch1-1", icon = icon("angle-right")),
      #menuSubItem("1.2", tabName = "ch1-2", icon = icon("angle-right")),
      #menuSubItem("1.3", tabName = "ch1-3", icon = icon("angle-right")),
      #menuSubItem("1.4", tabName = "ch1-4", icon = icon("angle-right"))
     ),       
     menuItem("Introduction", tabName = "intro", icon = icon("book")),       
     menuItem("Chapter 1", tabName = "ch1", icon = icon("bookmark-o")),       
     menuItem("Chapter 2", tabName = "ch2", icon = icon("bookmark-o")),
     menuItem("Chapter 3", tabName = "ch3", icon = icon("bookmark-o"))
     )
  ),
  body = dashboardBody(



 ),
)

---
This doesn't
---
ui <- dashboardPage(
  header = dashboardHeader(),
  sidebar = dashboardSidebar(
  collapsed = FALSE,
  sidebarMenu(
     menuItem("Preface", tabName = "preface", icon = icon("book")
     #menuItem("Chapter 1", tabName = "ch1", icon = icon("mortar-board"),
      #menuSubItem("1.1", tabName = "ch1-1", icon = icon("angle-right")),
      #menuSubItem("1.2", tabName = "ch1-2", icon = icon("angle-right")),
      #menuSubItem("1.3", tabName = "ch1-3", icon = icon("angle-right")),
      #menuSubItem("1.4", tabName = "ch1-4", icon = icon("angle-right"))
     ),       
     menuItem("Introduction", tabName = "intro", icon = icon("book")),       
     menuItem("Chapter 1", tabName = "ch1", icon = icon("bookmark-o")),       
     menuItem("Chapter 2", tabName = "ch2", icon = icon("bookmark-o")),
     menuItem("Chapter 3", tabName = "ch3", icon = icon("bookmark-o"))
     )
  ),
  body = dashboardBody(

  tabItems(
    #---Intro---#
    tabItem(tabName = "preface",
      fluidPage(
        h3("Preface"),
      )
    ),
    #---Intro---#
    tabItem(tabName = "intro",
      fluidPage(
        h3("Introduction"),
      )
    ),
  )

 ),
)

**Comment by DivadNojnarg** [comment]
I am not sure to follow but it works well:

```r
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)

ui <- dashboardPage(
  header = dashboardHeader(leftUi = tagList(actionButton("updateSidebarMenu", "Update menu"))),
  sidebar = dashboardSidebar(
    collapsed = FALSE,
    sidebarMenu(
      id = "sidebarmenuId",
      menuItem("Preface", tabName = "preface", icon = icon("book")),       
      menuItem("Introduction", tabName = "intro", icon = icon("book"))
    )
  ),
  body = dashboardBody(
    
    tabItems(
      #---Intro---#
      tabItem(
        tabName = "preface",
        fluidPage(
          h3("Preface")
        )
      ),
      #---Intro---#
      tabItem(
        tabName = "intro",
        fluidPage(
          h3("Introduction")
        )
      )
    )
    
  )
)


server <- function(input, output, session) {
  observeEvent(input$updateSidebarMenu, {
    selected <- if (input$sidebarmenuId == "preface") {
      "intro"
    } else {
      "preface"
    }
    updateTabItems(session, "sidebarmenuId", selected = selected)
  })
}

shinyApp(ui, server)
```

**Comment by michael-keyes** [comment]
Hmm. I must have been making a mistake. Sorry I can't give you a clear reason for the error. I was missing things like:
header = dashboardHeader

that perhaps weren't needed in the past.

Thank you for your help
