### ISSUE TITLE
Link to new Demo?

### ISSUE THREAD

**Issue by lmsimp** [RinteRface/shinydashboardPlus#122]
The Demo linked to "See a demonstration here" on [https://rinterface.github.io/shinydashboardPlus/](https://rinterface.github.io/shinydashboardPlus/) links to [this old demo](https://rinterface.github.io/shinydashboardPlus/) that contains old functions that are now no longer part of your package - do you have a URL for the new demo i.e. the one that is found in v2 of the package?

**Comment by DivadNojnarg** [comment]
Not yet, unfortunately, I had to push the 2.0.0 earlier than expected to prevent it from being archived from CRAN. Some things are still not updated and I don't really have time to take care of it.

**Comment by lmsimp** [comment]
I personally would remove this link to the old code as is confusing for new users see [this post](https://stackoverflow.com/questions/66681250/function-dashboardpageplus-is-not-compatible-with-latest-shinydashboardplus-ve/66681534#66681534)

**Comment by bhogan-mitre** [comment]
The linked demo no longer works at this point:

![Screen Shot 2021-06-16 at 12 04 36 PM](https://user-images.githubusercontent.com/32336739/122254356-0b505980-ce9b-11eb-9cd4-06be16653c9b.png)
