### ISSUE TITLE
If we set rightSidebar custom width, body has been changet to the default 230px

### ISSUE THREAD

**Issue by sheynkler** [RinteRface/shinydashboardPlus#124]
I set rightSidebars width to 300px. If I close and open rightSidebar, body width (section content) has been changed to the default 230px. I also need to switch the body width to 300px.
```
    if (interactive()) {
  library(shiny)
  library(shinydashboard)
  library(shinydashboardPlus)
  
  shinyApp(
    ui = dashboardPagePlus(
      header = dashboardHeaderPlus(
        enable_rightsidebar = TRUE,
        rightSidebarIcon = "gears"
      ),
      sidebar = dashboardSidebar(),
      body = dashboardBody(
        "Lorem ipsum..."
      ),
      rightsidebar = rightSidebar(
        width = 300
      ),
      title = "DashboardPage"
    ),
    server = function(input, output) { }
  )
}
```
![i1](https://user-images.githubusercontent.com/10814543/114397127-a167bb00-9b9e-11eb-8dc4-cc2d8df2e986.png)
![i2](https://user-images.githubusercontent.com/10814543/114397174-acbae680-9b9e-11eb-8270-c4c3a1f010dd.png)

**Comment by DivadNojnarg** [comment]
Hi,

The problem has been fixed in v2.0.0 on CRAN.
