### ISSUE TITLE
dashboardFooter won't run when defined earlier (outside of ui)

### ISSUE THREAD

**Issue by williamlai2** [RinteRface/shinydashboardPlus#128]
For example this code:

```
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)

header <-  dashboardHeader()
sidebar <-  dashboardSidebar()
body <- dashboardBody()
footer <- dashboardFooter(left = "Left content", right = "Right content")

shinyApp(
  ui = dashboardPage(
    header,
    sidebar,
    body,
    footer
  ),
  server = function(input, output) { }
)
```

Produces this error:

> [1] "main-footer"
Error in tagAssert(controlbar[[2]][[1]], type = "aside", class = "control-sidebar") : 
  Expected an object with class 'shiny.tag'.

It is based on the code [in the example here](https://rinterface.github.io/shinydashboardPlus/articles/controlbar.html), but defined earlier (like you would when you have a lot in the app).

**Comment by DivadNojnarg** [comment]
This is coming from the `dashboardPage` parameters order:

```r
dashboardPage(header, sidebar, body, controlbar = NULL, footer = NULL, ...)
```

The error would go away if you specify `controlbar = NULL or NULL` before putting the footer. Currently, footer is passed to the controlbar parameter causing the stop.

**Comment by williamlai2** [comment]
Thanks. That fixed it.
