### ISSUE TITLE
sidebarExpandOnHover doesn' trigger resize event

### ISSUE THREAD

**Issue by ismirsehregal** [RinteRface/shinydashboardPlus#143]
Using the [basic example](https://rinterface.github.io/shinydashboardPlus/articles/shinydashboardPlus.html) the sidebarExpandOnHover doesn't trigger a resize event. This behaviour isn't in line with the reaction triggered when hitting the burger-menu button:

![Animation](https://user-images.githubusercontent.com/36849480/123618028-1b0b5e80-d808-11eb-92d0-230015368ce2.gif)

Maybe an `overlay` arguement can be added as is was done for the `dashboardControlbar`

Related: https://github.com/RinteRface/shinydashboardPlus/issues/86

**Comment by DivadNojnarg** [comment]
Hi, 

This feature is intended as is in the original AdminLTE template, exactly like the controlbar overlay. It is not supposed to trigger a resize event, which is also the case in AdminLTE3 and bs4Dash: https://adminlte.io/themes/v3/.
