### ISSUE TITLE
dynamic footer

### ISSUE THREAD

**Issue by BirongZhang** [RinteRface/shinydashboardPlus#173]
Dear all,

Thanks for developing such as useful tool! Brilliant work!

I am quite interested about the footer of the [second example app](https://rinterface.github.io/shinydashboardPlus/). I found [dashboardFooter](https://search.r-project.org/CRAN/refmans/shinydashboardPlus/html/dashboardFooter.html), but this one is static.

I was wondering how to build a dynamic footer. For example, you put a picture or some text on the footer, and when the user clicks on the footer, it can take you to another linked website. Just like this:
<img width="699" alt="Screenshot 2022-10-19 at 21 49 22" src="https://user-images.githubusercontent.com/74430395/196801951-1e4df099-287b-48f0-8387-d7c7edb7e408.png">

Any advices would be highly appreciated! Thanks.

Kind regards,
Birong

**Comment by ismirsehregal** [comment]
I left an example [here](https://github.com/rstudio/shinydashboard/issues/391#issuecomment-1294026845).
