### ISSUE TITLE
How to completely collapse sidebar

### ISSUE THREAD

**Issue by byadu** [RinteRface/shinydashboardPlus#19]
I need the flipBox and rightsidebar for which I need shinydashboardPlus. 

I have a sidebar without icons, which I need to collapse completely, like that in shinydashboard. 

Is this possible?

Thanks

(A not so related issue but within the same code is that flipBox doesn't work within renderUI, but I can work around that by putting it in ui.R.)

**Comment by DivadNojnarg** [comment]
Hi,

this is because of this custom CSS in the dashboardPagePlus. I pushed a new version on GitHub:

```r
devtools::install_github("RinteRface/shinydashboardPlus")
```

```r
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)

shinyApp(
  ui = dashboardPagePlus(
    header = dashboardHeaderPlus(
     enable_rightsidebar = TRUE,
     rightSidebarIcon = "gears"
    ),
    sidebar = dashboardSidebar(),
    sidebar_fullCollapse = TRUE,
    body = dashboardBody(),
    rightsidebar = rightSidebar(),
    title = "DashboardPage"
  ),
  server = function(input, output) { }
)
```

Just pass sidebar_fullCollapse = TRUE to have the same behavior as in shinydashboard.
