### ISSUE TITLE
flipBox id has to be numeric?

### ISSUE THREAD

**Issue by vinpogo** [RinteRface/shinydashboardPlus#23]
the documentation states that the id for a flipBox has to be unique.
Therfore i gave the flipBox in my App a unique id and constantly got an error message: "Warning: Error in +: non-numeric argument to binary operator"
After Trial and error i found out that giving a numeric id will work. 

Also after finding out i have to give numeric ID's i wanted to include a flipBox into a shiny module. But giving the flipBox a numeric id inside of the modules namespace i get the same Error message as before.

Now my question is:
1) Is this behaviour by design or is it a Bug?
2) is it possible to use a flipBox inside of a shiny module? If, yes how would i do it?

**Comment by DivadNojnarg** [comment]
Hi vinpogo,
flipBox is a recent feature that has not been deeply tested. Moreover, a lot of people don't use modules when they just build simple apps. Therefore thanks for your report! 
I am terribly busy at the moment but I will have a look as soon as I have free time.
David
