### ISSUE TITLE
Change left sidebar behavior to normal shinydashboard

### ISSUE THREAD

**Issue by serkserk** [RinteRface/shinydashboardPlus#24]
Hi, first thanks for you library, there is lots of uselfull new widget !

One issue I have currently is that I want to use the default looking left sidebar, without the preview on hover or the main title collapsing or even allow to close it completly.
Those things doesn't seems possible right now.
Maybe I'm wrong.

**Comment by DivadNojnarg** [comment]
Hi,

this is because of this custom CSS in the dashboardPagePlus. I pushed a new version on GitHub:

```r
devtools::install_github("RinteRface/shinydashboardPlus")
```

```r
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)

shinyApp(
  ui = dashboardPagePlus(
    header = dashboardHeaderPlus(
     enable_rightsidebar = TRUE,
     rightSidebarIcon = "gears"
    ),
    sidebar = dashboardSidebar(),
    sidebar_fullCollapse = TRUE,
    body = dashboardBody(),
    rightsidebar = rightSidebar(),
    title = "DashboardPage"
  ),
  server = function(input, output) { }
)
```

Just pass sidebar_fullCollapse = TRUE to have the same behavior as in shinydashboard.
