### ISSUE TITLE
shinydashboardPlus and angular

### ISSUE THREAD

**Issue by RAnalytix** [RinteRface/shinydashboardPlus#26]
I am using shinydashboard plus for my shiny app. I embed shiny app in angular UI, using Iframes. But it will refresh automatically again and again. How to stop this?

**Comment by DivadNojnarg** [comment]
Can you provide a reproducible example please?

**Comment by RAnalytix** [comment]
[shinydashboard and Angular.zip](https://github.com/RinteRface/shinydashboardPlus/files/2758086/shinydashboard.and.Angular.zip)

The related Images and video are included in above ZIP file.

**Comment by DivadNojnarg** [comment]
I need a .R file please

**Comment by RAnalytix** [comment]
#27

**Comment by RAnalytix** [comment]
Code is same for both issue

**Comment by DivadNojnarg** [comment]
Can you try to set enable_preloader = FALSE  in `dashboardPagePlus()`?

**Comment by RAnalytix** [comment]
I set enable_preloader = FALSE the bouncing of UI is stopped. But made some changes in Iframe of angular side the shiny app looks better than previous. Actually, this is my 10th shiny App and the first time I was faced such an issue.
Thanks for the support.
