### ISSUE TITLE
disable the {min-height: 611px} property in body

### ISSUE THREAD

**Issue by yenzichun** [RinteRface/shinydashboardPlus#31]
hi,
While searching r shiny dashboard, I found your package very, very useful!

But now I'm facing a problem, which is when I want to create a map on the dashboard, there are some blank part at the bottom.
![image](https://user-images.githubusercontent.com/6956697/53281731-804a7300-3768-11e9-92ad-8e01670cbd4b.png)

I want the map to be fill the whole browser, without the scroll on the right side.

While checking with the inspector, I found that if I can disable the **property{min-height: 611px}** in the body, then the problem is fixed.
![image](https://user-images.githubusercontent.com/6956697/53281716-5b560000-3768-11e9-88ca-eb75027fed43.png)

But I don't know where I can adjust that property. Seems like it's automatically assigned when creating the shiny app. Is there a work-around to solve this?

Here's the sample code:
```r
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
library(dplyr)
library(leaflet)

header <- dashboardHeaderPlus(
    titleWidth = 200,
    enable_rightsidebar = TRUE,
    rightSidebarIcon = "gears"
)
sidebar <-  dashboardSidebar(
    width = 200,
    sidebarMenu(
        id = "tabs",
        menuItem("Map", tabName = 'map1',
                 icon = icon("map-marked-alt")
        )
    )
)
body <- dashboardBody(
    tags$head(
        tags$style(HTML('
                        #myMap {height: calc(90vh) !important;}
                        .content, .container-fluid {padding: 0px;}
                        '))
        ),
    fluidPage(
        leafletOutput("myMap")
    )
)

ui <- dashboardPagePlus(
    header,
    sidebar,
    body,
    collapse_sidebar = T,
    rightsidebar = rightSidebar(),
    skin="green"
)

server <- function(input, output, session) {
    output$myMap = renderLeaflet({
        leaflet(options = leafletOptions(zoomControl = FALSE)) %>% 
            addProviderTiles(providers$Wikimedia)
    })
}

shinyApp(ui, server)
```

Thank you in advance!

**Comment by DivadNojnarg** [comment]
It is coming from `{shinydashboard}` that sets the value inside `dashboardPage`.
