### ISSUE TITLE
reset/reopen closed boxPlus

### ISSUE THREAD

**Issue by ivokwee** [RinteRface/shinydashboardPlus#38]
Can we programatically reset/reopen boxes that were closed by the user? thanks. ivo.

**Comment by tsolloway** [comment]
Good question. It's why I stay away from that feature. Another way around it is utilizing shinyjs 's show/ hide functionality

**Comment by rrpaleja** [comment]
Has anyone found an answer to this?

**Comment by DivadNojnarg** [comment]
Yes it is possible but not included yet. The bs4Dash package does it (Bootstrap 4 shinydashboard)

**Comment by DivadNojnarg** [comment]
Fixed in latest devel version. Just use the `updateBox` function passing the `restore` action:

```r
updateBox(
        "mybox", 
        action = "restore"
      )
```
