### ISSUE TITLE
Left sidebar collapse/expand icon

### ISSUE THREAD

**Issue by DavidPatShuiFong** [RinteRface/shinydashboardPlus#39]
I find there is a problem with the collapse/expand icon for the left sidebar. This is what it looks like, for shinydashboardPlus 0.7.5, using *shinydashboardPlusGallery()* and using Microsoft Windows 10.

With Edge 42.17134.1.0:

![image](https://user-images.githubusercontent.com/8335820/58759489-45798780-856e-11e9-9b7d-881874ccb2a3.png)

With Firefox 67.0:

![image](https://user-images.githubusercontent.com/8335820/58759514-adc86900-856e-11e9-9b82-e4ca5bdd377a.png)

and probably what it is supposed to look like, in Chrome 74.0.3729.169:

![image](https://user-images.githubusercontent.com/8335820/58759516-c2a4fc80-856e-11e9-8edf-617862a3125c.png)

**Comment by DivadNojnarg** [comment]
Hi @DavidPatShuiFong: which version of shiny are you currently using?

**Comment by DavidPatShuiFong** [comment]
My apologies, the version of shinydashboard I was using was `0.7.0`, and the version of shiny was `1.3.0` (this was a MRAN snaphsot for Microsoft R Open `3.5.1`, not the first time I've been caught out by older packages).

The problem was fixed in shinydashboard `0.7.1`, as reference in https://github.com/rstudio/shinydashboard/issues/297

Upgrading to shinydashboard `0.7.1` fixed the missing hamburger problem. My apologies for the false alarm!

**Comment by DavidPatShuiFong** [comment]
> 
> 
> Hi @DavidPatShuiFong: which version of shiny are you currently using?
> 
> Could you do the following for me (see image below):
> 
>     * open the web inspector and give me the class of the sidebar toggle icon.
> 
> 
> <img alt="Capture d’écran 2019-06-03 à 19 17 56" width="637" src="https://user-images.githubusercontent.com/18291543/58820994-5987bc80-8634-11e9-810c-66241cc759bd.png">
> 
> My guess is that the class would be something like "fas fa-bars" instead of "fa fa-bars"...

![image](https://user-images.githubusercontent.com/8335820/58944475-435d3600-87c5-11e9-93ed-330313230d0a.png)

it was "fa fa-bars"
