### ISSUE TITLE
boxPlus() request sidebar_icon

### ISSUE THREAD

**Issue by jmw86069** [RinteRface/shinydashboardPlus#40]
First, great work on this package and thank you for making it available for others!

I love the boxPlus() with the sidebar, I am using it to allow users to customize plot visualization settings. However, the icon "i" is more consistent with "info" for more information, and not "config" for configuration.

I noticed it defined an icon `shiny::icon("info")` and wondered if the icon could be a function argument, similar to how `dropdown_icon` is a function argument.

Thank you!

**Comment by DivadNojnarg** [comment]
Hi James,

thanks for using the package. Try reinstall the devel version and let me know:

```r
devtools::install_github("RinteRface/shinydashboardPlus")
```

**Comment by jmw86069** [comment]
I really appreciate this new feature! I have tested and confirm it works how I had hoped.

*Apologies for the long delay in responding!*

For now I'll use the Github version.
