### ISSUE TITLE
Icon at the shinydashboard header

### ISSUE THREAD

**Issue by jciturras** [RinteRface/shinydashboardPlus#44]
hi!

Thanks for your package. I want to know hoy did you place the shinydashboard+ logo as a dynamic image that changes when you colapse the header. It's great and i wan to do the same with my app. 

I looked up the HTML code, but i did not realize how to do it in R.

thank!

**Comment by DivadNojnarg** [comment]
Please have a look at #6 
https://github.com/RinteRface/shinydashboardPlus/issues/6
