### ISSUE TITLE
shinydashboardPlus +  ggplotly = problem in Shiny server

### ISSUE THREAD

**Issue by jciturras** [RinteRface/shinydashboardPlus#45]
Hi,

I'm developing a shiny app and i tried serveral times to upload a my app on shinyserver. 

My plots are rendered using ggplotly. When I run my app on my laptop it works, but when I use deployApp() and then try to render the graphs online, it doesn't work

¿do you know if shinydashboardPlus has problems on this matter?

thanks!

**Comment by DivadNojnarg** [comment]
Do you have any reproducible example?
