### ISSUE TITLE
Can't able to deploy shiny App on Rstudio Connect

### ISSUE THREAD

**Issue by kmaheshkulkarni** [RinteRface/shinydashboardPlus#58]
Error:-
Attaching package: ‘shinydashboard’
The following object is masked from ‘package:graphics’:
box
Error in value[3L] :
there is no package called ‘shinydashboardPlus’
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne ->
Execution halted
![Error Shinydashboard](https://user-images.githubusercontent.com/18054137/66999902-73fa9800-f0f4-11e9-8463-150d68bb5348.png)

**Comment by DivadNojnarg** [comment]
This is not related to shinydashboardPlus. Alternatively, you may try to install shinydashboardPlus from GitHub and retry the deployment.
