### ISSUE TITLE
Error issues about column width with 'column' in shiny

### ISSUE THREAD

**Issue by SeungminHeo** [RinteRface/shinydashboardPlus#60]
Hi.

I'm using your ShinydashboardPlus package, I re-write my shinyapp code with your package.

But I found an error with column width.

this is my example code about layout in body section

```
tab_kpi <- function() {
  list(
    fluidPage(
      fluidRow(
        id = "row_title",
        column(width = 5, 
               id = "col_title",
               h4("example")
        )
      )
    )
  )
}
```
At first run, no error occurs, but after that `column width must be between 1 and 12` error occurs.

Is there any solution to this error?

**Comment by DivadNojnarg** [comment]
can You provide a reprex?
