### ISSUE TITLE
GradientBox colours not working

### ISSUE THREAD

**Issue by fcecinati** [RinteRface/shinydashboardPlus#72]
Hello! 

I have tried to use gradientBox from many devices and every time I encounter the same problem: they render correctly using gradientColor with some colours (e.g. 'blue', 'maroon', or 'yellow'), but it doesn't work with others (e.g. 'orange, 'gray' or 'olive'). 
In particular, when it is not rendering correctly, the 'x' element to close the box is coloured correctly, but the rest of the header is white. 

Minimum reproducible example:

```
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)

ui <- dashboardPage(
    dashboardHeader(),
    dashboardSidebar(),
    dashboardBody(
        gradientBox(title='Box',
                    gradientColor='yellow',
                    icon='fa fa-sort-numeric-asc',
                    width=12,
                    footer=list(h4('Hello')))
    )
)
server <- function(input, output) {}
shinyApp(ui = ui, server = server)
```

Produces this result:
![image](https://user-images.githubusercontent.com/8179868/75607719-0030b900-5af2-11ea-838b-1f125e956a10.png)

While changing colour:

```
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)

ui <- dashboardPage(
    dashboardHeader(),
    dashboardSidebar(),
    dashboardBody(
        gradientBox(title='Box',
                    gradientColor='olive',
                    icon='fa fa-sort-numeric-asc',
                    width=12,
                    footer=list(h4('Hello')))
    )
)
server <- function(input, output) {}
shinyApp(ui = ui, server = server)
```

Produces the following:

![image](https://user-images.githubusercontent.com/8179868/75607739-29514980-5af2-11ea-8d64-db2ae481c354.png)

Is there a way to solve this problem?
Thank you!!

**Comment by DivadNojnarg** [comment]
According to the adminLTE2 [CSS file](https://github.com/ColorlibHQ/AdminLTE/blob/v2/dist/css/AdminLTE.css) (from line 5245-5334), there are only: **teal, blue, light-blue, aqua, yellow, purple, green, red, black and maroon** ... that are **supported for gradient colors**. olive does not belong to the list of gradient colors, even though it is a color of the adminLTE theme (see below). Therefore, it cannot work and this is the reason why you only see the collapse icon color changing. 

Below is the full list of colors:

```css
.bg-red,
.bg-yellow,
.bg-aqua,
.bg-blue,
.bg-light-blue,
.bg-green,
.bg-navy,
.bg-teal,
.bg-olive,
.bg-lime,
.bg-orange,
.bg-fuchsia,
.bg-purple,
.bg-maroon,
.bg-black,
.bg-red-active,
.bg-yellow-active,
.bg-aqua-active,
.bg-blue-active,
.bg-light-blue-active,
.bg-green-active,
.bg-navy-active,
.bg-teal-active,
.bg-olive-active,
.bg-lime-active,
.bg-orange-active,
.bg-fuchsia-active,
.bg-purple-active,
.bg-maroon-active,
.bg-black-active,
```

You see that a lot are not part of the gradient CSS, unfortunately.

**Comment by fcecinati** [comment]
Thank you! 
Your list is very helpful.
However, it may be worth updating the help for gradientBox, because it currently links to the page: 
[https://adminlte.io/themes/AdminLTE/pages/UI/general.html](https://adminlte.io/themes/AdminLTE/pages/UI/general.html)
for the choice of colours, where more colours are listed (including orange and grey for example).

Any chance in the future more colours will be included for gradientBox? The limited selection is too restricting for many app customisations.

Thank you!
