### ISSUE TITLE
Opening the right sidebar doesn' trigger resize event

### ISSUE THREAD

**Issue by ismirsehregal** [RinteRface/shinydashboardPlus#86]
Coming from [here](https://stackoverflow.com/questions/63832380/stop-the-right-sidebar-in-shinydashboardplus-from-hiding-the-body-of-the-app).

I'm not sure if this behaviour is intended or not, but currently when opening the right sidebar plots aren't resized. However, they are resized once the browser window is resized:

![problem](https://user-images.githubusercontent.com/36849480/92898586-65108880-f41e-11ea-8d3a-b459bb35b004.gif)

To me it seems it is quite the same issue as [this one](https://github.com/rstudio/shinydashboard/issues/62) in `shinydashboard`

I adapted their fix for the right sidebar (comment out the script tag to reproduce the issue):

```
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)

header <- dashboardHeaderPlus(enable_rightsidebar = TRUE,
                              rightSidebarIcon = "filter")

sidebar <- dashboardSidebar()
body <- dashboardBody(
  tags$script('
      $(".navbar-custom-menu").on("click",function(){
        $(window).trigger("resize");
      })'
  ),
  fluidPage(
    plotOutput(
      "scatter",
      height = "700px",
      width = "100%"
    )
  ))

rightsidebar <- rightSidebar()

ui <- dashboardPagePlus(header,
                        sidebar,
                        body,
                        rightsidebar)

server <- function(input, output) {
  output$scatter <- renderPlot({
    plot(1:10)
  })
}

shinyApp(ui, server)
```
Which results in the expected behaviour:
![expected](https://user-images.githubusercontent.com/36849480/92899192-e2d49400-f41e-11ea-9b1e-7e70ee1f72b3.gif)

**Comment by ismirsehregal** [comment]
#85 was it a duplicate? I'm confused.

**Comment by DivadNojnarg** [comment]
Nope. I closed the wrong issue
