### ISSUE TITLE
dashboardFooter

### ISSUE THREAD

**Issue by Famondir** [RinteRface/shinydashboardPlus#92]
Hi all,
I just tried to use the footer in a shinydashboardPlus. Running the minimal example results in this error:
`Error in dashboardPage(header = dashboardHeader(), sidebar = dashboardSidebar(),  : 
  unused argument (footer = dashboardFooter(left = "By Divad Nojnarg", right = "Zurich, 2019"))`

When I tried to use it in my page before the error was:
`Error in match.arg(skin) : 'arg' must be NULL or a character vector`

I'm using RStudio 1.3.1073, R 4.0.2 and Windows 10 x64 18363
Can anyone help me out?

**Comment by DivadNojnarg** [comment]
Hi,

Are you loading `shinydashboardPlus` after `shinydashboard`?

**Comment by Famondir** [comment]
Yeah. That was the way I was loding these packages. Since it's a while I tried to use the footer I'm not sure 100 %. But I think the order was as follows:

```library(shiny)
library(shinyWidgets)
library(shinydashboard)
library(shinydashboardPlus)
library(shinybusy)```

**Comment by DivadNojnarg** [comment]
This is what I have with the latest development version:

```r
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)

ui <- dashboardPage(
  preloader = list(html = waiter::spin_1(), color = "#333e48"),
  header = dashboardHeader(),
  sidebar = dashboardSidebar(),
  body = dashboardBody(
    box(plotOutput("plot"), collapsible = TRUE)
  ), 
  footer = dashboardFooter("David")
)

server <- function(input, output) {
  output$plot <- renderPlot({
    plot(mtcars)
  })
}

shinyApp(ui, server)
```
