### ISSUE TITLE
Bug: updating boxes

### ISSUE THREAD

**Issue by amar00k** [RinteRface/shinydashboardPlus#94]
Updating boxes doesn't work as intended due to a bug in shinydashboardPlus.js lines 649-651:

`$(el).parent().find("script[data-for='" + el.id + "']").replaceWith(
   '<script type="application/json" data-for="mybox">' + JSON.stringify(config) + '</script>'
)`

Should be replaced by:

`$(el).parent().find("script[data-for='" + el.id + "']").replaceWith(
   '<script type="application/json" data-for="' + el.id + '">' + JSON.stringify(config) + '</script>'
)`

**Comment by DivadNojnarg** [comment]
Well spotted! Thanks
