### ISSUE TITLE
update validColors

### ISSUE THREAD

**Issue by bhogan-mitre** [RinteRface/shinydashboardPlus#97]
I believe there's a disconnect between the documentation for `box` parameter `background` which [suggests that `gray_lte` is an option](https://github.com/RinteRface/shinydashboardPlus/blob/master/R/boxes.R#L44) and the current definition of [`validColors`](https://github.com/RinteRface/shinydashboardPlus/blob/master/R/utils.R#L117).

```
> shinydashboardPlus::box(background = "gray_lte") 
Error in validateColor(background) :  
  Invalid color: gray_lte. Valid colors are: red, yellow, aqua, blue, light-blue, green, navy, teal, olive, lime, orange, fuchsia, purple, maroon, black.
```

Also I'm curious how that compares to the gray that is defined in the included CSS.
https://github.com/RinteRface/shinydashboardPlus/blob/master/inst/shinydashboardPlus-0.6.0/css/AdminLTE.css#L4466-L4469

Is there anything technical preventing the inclusion of `gray` and `light-gray` in `validColors`?  Thank you for considering.

**Comment by DivadNojnarg** [comment]
You're right, `gray_lte` does not exist. This is actually `gray` and missing from `validColors`. There are also `active` nuances as mentioned here : https://adminlte.io/themes/AdminLTE/pages/UI/general.html, like `bg-gray-active` which is slightly darker than the `bg-gray` (but ugly quite frankly). For `gray-light` the contrast is really bad. I'll include gray in the available colors.

**Comment by DivadNojnarg** [comment]
Same thing, there is a typo for `light_blue` that is actually `light-blue`

**Comment by bhogan-mitre** [comment]
Great, thanks @DivadNojnarg!
